Resolve error CS0266: Cannot implicitly convert type 'bool?' to 'bool' for AL v16.0.1743592 (#1145)
* Resolve error CS0266: Cannot implicitly convert type 'bool?' to 'bool' for AL v16.0.1743592

* Fix failing tests

(cherry picked from commit d5afc9caebce1df45dac86c65d7e6b087320f94a)